version: '3.8'

services:
  graphdb:
    image: khaller/graphdb-free
    container_name: graphdb-free
    ports:
      - "7200:7200"
    environment:
      - JVM_OPTS=-Xmx4g 
    volumes:
      - ./:/opt/graphdb/home/data

 