version: '3.8'

services:
  app-prod-worker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
