version: '3.8'

services:
  app-dev-worker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - ENVIRONMENT=debug
    restart: on-failure
    networks:
      - webnet

networks:
  webnet:
    driver: bridge