services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
      - '5678:5678'
    restart: always
    depends_on:
      - ollama
      - db
    environment:
      - OLLAMA_HOST=http://ollama:11434
    env_file: 
      - ./brain2kg/api/.env.development
    
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - '11434:11434'
    volumes:
      - ./ollama:/root/.ollama
      - ~/.ollama/models:/root/.ollama/models
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0

  db:
    container_name: db
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    env_file: 
      - ./brain2kg/api/.env.development

volumes:
  db:
    driver: local