version: '3.8'

services:
  app-dev-query_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=debug
    restart: on-failure



