version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # RabbitMQ default port
      - "15672:15672" # RabbitMQ Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persist data
    environment:
      RABBITMQ_DEFAULT_USER: "admin_decentralized_test"
      RABBITMQ_DEFAULT_PASS: "R@admdoM81_1"

volumes:
  rabbitmq_data:
