version: '3.8'

services:
  app-brainypedia-tokenmanager-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
    driver: bridge