version: '3.8'

services:
  app-brainypedia-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8055:8000"
    environment:
      - ENVIRONMENT=debug
    restart: on-failure
    volumes:
      - ./:/app

    networks:
      - webnet

networks:
  webnet:
    driver: bridge