version: '3.8'

services:
  app-brainypedia-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8055:8055"
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped

    networks:
      - webnet

networks:
  webnet:
    driver: bridge